name: build_and_test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        compiler: [g++-12, g++-14, clang++-14, clang++-17]
        cpp_standard: [20]
        build_type: [Debug, Release]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install ninja-build

          if [[ "${{ matrix.compiler }}" == g++-12* ]]; then
            sudo apt-get install gcc-12
          elif [[ "${{ matrix.compiler }}" == g++-14* ]]; then
            sudo apt-get install gcc-14
          elif [[ "${{ matrix.compiler }}" == clang++-14* ]]; then
            sudo apt-get install clang-14
          elif [[ "${{ matrix.compiler }}" == clang++-17* ]]; then
            sudo apt-get install clang-17
          fi
      - name: Configure CMake
        run:  |
          cmake . -DKELCORO_ENABLE_TESTING=ON             \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}}     \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}}     \
            -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}} \
            -B build -G "Ninja"
      - name: Build
        run:
          cmake --build build

      - name: Test
        run: |
          cd build
          ctest --output-on-failure -C ${{matrix.build_type}} -V
      - name: Configure CMake (ASAN)
        run:  |
          cmake . -DKELCORO_ENABLE_TESTING=ON             \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}}     \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}}     \
            -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}} \
            -DKELCORO_ENABLE_ASAN=ON                \
            -B build_asan -G "Ninja"
      - name: Build (ASAN)
        run:
          cmake --build build_asan

      - name: Test (ASAN)
        run: |
          cd build_asan
          ctest --output-on-failure -C ${{matrix.build_type}} -V
